[package]
name = "git_management"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "A library for managing git repositroies"
documentation = "Documentation/"
license = "MIT"

[dependencies]
colour = "0.6.0"
